### ISSUE TITLE
Could not install requirements

### ISSUE THREAD

**Issue by jaonoctus** [eddieoz/youtube-clips-automator#1]
## Description

First I tried to run `pip install -r requirements`,

```
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements'
```

Then, tried `pip install -r requirements.txt`

```
Collecting absl-py==0.13.0
  Using cached absl_py-0.13.0-py3-none-any.whl (132 kB)
Collecting aiohttp==3.8.1
  Using cached aiohttp-3.8.1-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.3 MB)
Collecting aiosignal==1.2.0
  Using cached aiosignal-1.2.0-py3-none-any.whl (8.2 kB)
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3103, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/packaging/requirements.py", line 101, in __init__
    raise InvalidRequirement("Invalid URL given")
pkg_resources.extern.packaging.requirements.InvalidRequirement: Invalid URL given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/install.py", line 357, in run
    resolver.resolve(requirement_set)
  File "/usr/lib/python3/dist-packages/pip/_internal/legacy_resolve.py", line 177, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/usr/lib/python3/dist-packages/pip/_internal/legacy_resolve.py", line 333, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/lib/python3/dist-packages/pip/_internal/legacy_resolve.py", line 270, in _get_abstract_dist_for
    skip_reason = self._check_skip_installed(req)
  File "/usr/lib/python3/dist-packages/pip/_internal/legacy_resolve.py", line 228, in _check_skip_installed
    req_to_install.check_if_exists(self.use_user_site)
  File "/usr/lib/python3/dist-packages/pip/_internal/req/req_install.py", line 443, in check_if_exists
    self.satisfied_by = pkg_resources.get_distribution(str(no_marker))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 480, in get_distribution
    dist = Requirement.parse(dist)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3150, in parse
    req, = parse_requirements(s)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3096, in parse_requirements
    yield Requirement(line)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3105, in __init__
    raise RequirementParseError(str(e))
pkg_resources.RequirementParseError: Invalid URL given
```

## Environment
- Python version: `3.8.10`
- ffmpeg version: `4.2.4`
- OS: `5.10.16.3-microsoft-standard-WSL2`

**Comment by eddieoz** [comment]
Hello @jaonoctus
I recovered the requirements.txt from a previous commit and merged. Try again, please.

**Comment by jaonoctus** [comment]
Fixed for me! thanx

```
Collecting Pillow
  Downloading Pillow-9.1.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.3 MB)
     |████████████████████████████████| 4.3 MB 3.2 MB/s
Collecting audiotsm
  Downloading audiotsm-0.1.2-py2.py3-none-any.whl (32 kB)
Collecting scipy
  Downloading scipy-1.8.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (41.6 MB)
     |████████████████████████████████| 41.6 MB 62.4 MB/s
Requirement already satisfied: numpy in /usr/lib/python3/dist-packages (from -r requirements.txt (line 4)) (1.17.4)
Collecting pytube
  Downloading pytube-12.0.0-py3-none-any.whl (56 kB)
     |████████████████████████████████| 56 kB 9.5 MB/s
Installing collected packages: Pillow, audiotsm, scipy, pytube
  WARNING: The script pytube is installed in '/home/jaonoctus/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed Pillow-9.1.0 audiotsm-0.1.2 pytube-12.0.0 scipy-1.8.0
```
